# spring:
# datasource:
# url: jdbc:sqlserver://tradebull.database.windows.net:1433;database=tradebulldb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
# username: tradebull
# password: password@123
# jpa:
# show-sql: true
# hibernate:
# ddl-auto: update
# dialect : org.hibernate.dialect.SQLServer2012Dialect

# server.port: 9191
